### ISSUE TITLE
crash when require module with dash

### ISSUE THREAD

**Issue by birhoff** [enb-bem/enb-bemxjst#113]
If I require module with dash, like this:
```
{
sourceSuffixes: ['bemtree.js', 'bemtree'],
lang: '{lang}',
requires: {
    'my-module': {
        commonJS: path.resolve(__dirname + '/../my-module')
     }
}
```
I've got a crash, when try to require compiled bemtree in my App:
```
my-module: require("some/path/my-module")});
    ^

SyntaxError: Unexpected token -
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    // my code here
```

**Comment by arikon** [comment]
@birhoff Could you provide a PR with a fix?
